sudo: required

language: generic

service:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t wogud556/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true wogud556/docker-react-app npm run test -- -- coverage

after_success:
  - echo "Test Success"